spring.application.name=food-delivery

spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery
spring.datasource.username=postgres
spring.datasource.password=ashray
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=7fA2mN9xQ1vL8pR6tY4uK3wE5zH0cJdB9sX2gF7nM1qP
jwt.expiration=3600000